language: java

env:
  global:
    - secure: H5lzJBidY+SUWVLPKT/5NClD4t/Ap6EXbTGrNceg9CmHKjTiNYFLUc7jiIBOrfKXr/lYmIFB7ajkOaAL0EsoW/asFM7GLDW2zeUgNT2MuSCMx8sWUby06sDQuGuoIea3kOcw4AxScev2F6NBFszVxsxRbOCrDyykRlmwDL3M3Lt8tChnpGU/jIZx8g0RN5Rnk6EDumyavC1OFKr+ha0QWEabwCTqtyHJXTJEq4z8IWCtl+KJsZtThVeZ3NMbt+wq2X4l+1O0qHmpS/iYUm+mmr5WYowHsqtZq/Q0qkBI04QLTXpafmddCqo3XA1epEHVaVe7juFFWOvCbFzVn6ICfwk2bI2jnHcaydbXLO7UOLWeECs+TFyiqSDHOqz7Q+p70JV/JMXGAPNJsK5dp5um3PxujJCaX5r3f9THTNOx1wl5Y5HwarGT/0IEqNkC+pve8Zz+bWY3x9m/cSWOaOUgOPjTLI8kCWf2Shqf+i/qJq2Ah+QRRxX4jZFD38l+QDNvR/uKBBeyW9MnALPbqkPaYJhvLE34CS2kZedgdPxcayZXMzrmUBeiatMazgmdeZFwhWEa2YDz4OnFUqutH1LSBd6sGM8O4EX5znPkmiDzRsOzk/siuu+x8wjxGSuytVZ8r94e98kAGfFUh8iiuO5CMZvlk2ML6TwCQkeAjlcYoX0=
    - # ^^ OSSRH_JIRA_USERNAME
    - secure: NiHh9cejghTaMtXxvL6tZegRiqfwpjGG06TaqInI/x8At6EK2d/JQ9tkXDttGlmIHLI/x3SbwSAw3h0UfciCfIgmRZO4r0AnLgjaTzr1Q4TQRxcLNKP/A9L5uY2x3wIeKdxzFW0my/BljLUpmqu9guIITpcMN9jzgtBu2ZrbysXTyVbk8IXyrLLqOXfhQ13Q0M5g1EAO+D1hG7m3nTn5MzjbgVs1ZZKoOilvPH1iwJ5aQ3aOnotG6FXpHUVYZ22+UaIIe98NNZ6dvNbRxSQvXY+9gxbxl7A9uOcA8rZiMlUREXFJHMwCMv5yKUv+wQUKbYZmO0qB29qvLngrKWm0/BzXbvX4nLufUcfoQoqQvcaeRmZTlYqyJrafAUOSm8wE9K4295MSXuaFrzn/enf4Lne6ix5ytB1FauMa+30lVyzq4DdVz8vvIgSylepEduKArYC948JxU7AtN673ftBhBtPe9PkI+8eQYdf6AVmU6aNSe0TPtL85MShCswZrgdNhDB/JWleTv6ob2ryTZ5wd45p8edq3Ws+sCw1tIRiaWllltVvB3y+Ov/p7suRVEtVWGkBYlg6GnkTrSD6lx0njD7fQK52dP2Xl/b7lYccIW5nX3VMC1UIXj90uxdnVhyI9BNYPEWu2UUGgINJVeDDspiLqFbI8PzvLrMsK+3Vmd00=
    - # ^^ OSSRH_JIRA_PASSWORD
    - secure: htrjZUldgKn+u4DKvOrQZv15rM89Kkja8M0gzKNfG77Psby21YBlmOlE7Fuiw62x7PD3BUuUOO+/FyFTrs0cERRv+o95/rvd3psVa3Tucuk0aRJW2zRiW8obWljMTOg2+GGtCGEIAcRK65FR9zFpHwkBoN/bn7Ze7HtjYusaT/Ovvjf3lvakG9dspUdCNJIxV0iCw1BMqLc0M7C/MwEkP42Mjt/qs1sZj2iJUeUae/aWcxiR9zbZGsDaxYg3Dmk/byv8n0W9MyvYS/jo42QTGgvM3UndfoW5IqnyXXmQ2ghyHRiYjBtOk5HqwtpLZsgE0V2QtG+CcT2497JPVhW0fAJ8Qyf8GNDB3NWa24zKk2SyHO7HBmIpzFR3Kt/w84oBnDDt5m2gLsKMOFopN5CXdC1Th/CqbDTnD5VecU7lWMzrXpotEi8hkj1VrgB/9i9V6BM4izMiYabzuaiLPiMsyZozt5jykB0Q0H0n2LV6ZvbyCIDZ+rI8kSatXQyEDiFD9CxcQ9dl0KI9o59AI3I9ePCKABua1kzWZ+E0tMc3MMkbMizApRzjF0h1ZijV43nRnhgNuaya7tmsas5E9EkT0D7+VtAqQlfwNet/mOgxc7aeE9Cypkb7UKEiuGBQ1XM5eIUIVlVYLwHV6PbhEQIAoCYolkhKS4B2EJHA1pD/3Pg=
    - # ^^ GPG_KEY_NAME
    - secure: fGAcx6xzXGKZ9+yPM7JhQ40TD4dBE5vFCK9C5fp775s1JwPTAsHgQDJmO1Y8HcCCOoxE0YCoHm1F4OiOvu43yFS0TXJvrAYy7HvGSCVGbvsjxElLfngnAPU7s51Nl8AHthibgsfRU9geHghfNjbJg8K2qExj7gUnKoFwKU95lVT/5PxkcUUxlVXYXPFxOJ19Iy2I5hCPiFQdqrGpP7uj2FXnYyfblQEEt52uj44nBajCCuIiMJuxkwAPmc+WJvthqeyGooQaqsApWA1GdivcfatL4Br7TZCHAS1/mUTmbbtSCZ9ifGvs2suZxgZ1tzw5bAsiFhrdShUFOyXeuLFT9xVQ6NGLS5SJTUNnf4ZZB/bQkqERk88E+PBDAQXa+cw39ZiI61F9rW66Zg/7epAc5ARwa56CuZ7/AbQrJQMjQBfJqPGopfOqa5DxNit+5YfDcceNBJJfcG+GQFXgSLXF2YwvwEWV7FFBeiyvuM92A5PLdMWT2uBhOzxG0S85gsceThEsh65vEv4IVhP9eXv66SBb+NmZZ3Zji2k9v7y0F2qNqg5NkJb6Yph/VsA4py77INAtw3NPDe/iZNlluKvMuHKUrcrTdAAzOEnSXLYjlXK6gkgNp2MHod80gO1bcI81wJx8g0ekPfH/Fg9zNZp1tqDlUKhfKgk1F0FVHbsjQbc=
    - # ^^ GPG_PASSPHRASE

addons:
  apt:
    packages:
      - oracle-java8-installer
cache:
  directories:
    - $HOME/.m2
jdk:
  - oraclejdk8

script: mvn clean install

after_success:
  - chmod +x ./cd/deploy.sh
  - ./cd/deploy.sh
